export const FETCH_MOVIES_START = 'FETCH_MOVIES_START';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const DELETE_MOVIE_START = 'DELETE_MOVIE_START';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_ERROR = 'DELETE_MOVIE_ERROR';

export const CREATE_MOVIE_START = 'CREATE_MOVIE_START';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const CREATE_MOVIE_ERROR = 'CREATE_MOVIE_ERROR';

export const EDIT_MOVIE_START = 'EDIT_MOVIE_START';
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
export const EDIT_MOVIE_ERROR = 'EDIT_MOVIE_ERROR';

export const FILTER_MOVIES_START = 'FILTER_MOVIES_START';
export const FILTER_MOVIES_SUCCESS = 'FILTER_MOVIES_SUCCESS';
export const FILTER_MOVIES_ERROR = 'FILTER_MOVIES_ERROR';

export const SORT_MOVIES_START = 'SORT_MOVIES_START';
export const SORT_MOVIES_SUCCESS = 'SORT_MOVIES_SUCCESS';
export const SORT_MOVIES_ERROR = 'SORT_MOVIES_ERROR';
